# Generated by Django 4.2.5 on 2023-10-13 19:26

from django.db import migrations, models
import gestionElementos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numeroIdentificacion', models.CharField(max_length=20)),
                ('nombreCompleto', models.CharField(max_length=80)),
                ('fechaCumpleaños', models.DateField()),
                ('fechaExpedicion', models.DateField()),
                ('nota', models.CharField(max_length=500)),
                ('fechaExpiracionClave', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50, validators=[gestionElementos.models.validar_clave_segura])),
                ('nota', models.CharField(max_length=500)),
                ('fechaExpiracionClave', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Secreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('secreto', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50, validators=[gestionElementos.models.validar_clave_segura])),
                ('nota', models.CharField(max_length=500)),
                ('fechaExpiracionClave', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=30)),
                ('titular', models.CharField(max_length=30)),
                ('fechaVencimiento', models.CharField(max_length=30)),
                ('cvc', models.CharField(max_length=3)),
                ('clave', models.CharField(max_length=50, validators=[gestionElementos.models.validar_clave_segura])),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('nota', models.CharField(max_length=500)),
                ('fechaExpiracionClave', models.DateField()),
            ],
        ),
    ]
